name: fixers-in-greece
region: fra
static_sites:
- name: fixers-in-greece
  github:
    repo: Gen-Plus-group/fixers-in-greece
    branch: main
    deploy_on_push: true
  source_dir: /
  build_command: ./build.sh
  output_dir: /