name: fixers-in-greece
region: fra
static_sites:
- name: fixers-in-greece-static
  source_dir: /
  output_dir: /
  build_command: npm install && npm run build-css-prod
  environment_slug: node-js
  routes:
  - path: /